# Generated by Django 6.0.4 on 2026-04-17 12:52

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProducerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(help_text='Tell customers about your farm and produce.')),
                ('farming_method', models.CharField(choices=[('organic', 'Organic'), ('conventional', 'Conventional'), ('biodynamic', 'Biodynamic'), ('free_range', 'Free Range'), ('regenerative', 'Regenerative Agriculture'), ('mixed', 'Mixed Methods')], default='conventional', max_length=30)),
                ('location', models.CharField(help_text="General area (e.g. 'Near Chorley, Lancashire')", max_length=200)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='producers/')),
                ('website_url', models.URLField(blank=True)),
                ('is_verified', models.BooleanField(default=False, help_text='Admin-verified producer.')),
                ('joined', models.DateField(default=django.utils.timezone.now)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='producer_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Producer Profile',
                'verbose_name_plural': 'Producer Profiles',
                'ordering': ['business_name'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('address_line_1', models.CharField(blank=True, max_length=255)),
                ('address_line_2', models.CharField(blank=True, max_length=255)),
                ('town_city', models.CharField(blank=True, max_length=100)),
                ('county', models.CharField(blank=True, max_length=100)),
                ('postcode', models.CharField(blank=True, max_length=10)),
                ('loyalty_points', models.PositiveIntegerField(default=0)),
                ('loyalty_tier', models.CharField(choices=[('seedling', 'Seedling'), ('sapling', 'Sapling'), ('oak', 'Oak'), ('elder', 'Elder')], default='seedling', max_length=20)),
                ('gdpr_consent', models.BooleanField(default=False)),
                ('gdpr_consent_date', models.DateTimeField(blank=True, null=True)),
                ('marketing_opt_in', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
            },
        ),
    ]
