# Generated by Django 6.0.4 on 2026-04-17 12:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='categories/')),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('unit', models.CharField(choices=[('each', 'Each'), ('kg', 'Per kg'), ('100g', 'Per 100g'), ('litre', 'Per litre'), ('500ml', 'Per 500ml'), ('dozen', 'Per dozen'), ('bunch', 'Per bunch'), ('loaf', 'Per loaf'), ('jar', 'Per jar'), ('bottle', 'Per bottle')], default='each', max_length=20)),
                ('stock_quantity', models.PositiveIntegerField(default=0)),
                ('is_available', models.BooleanField(default=True)),
                ('origin', models.CharField(blank=True, help_text='Where this product was grown / produced.', max_length=200)),
                ('certifications', models.CharField(blank=True, help_text='e.g. Organic Soil Association, Red Tractor', max_length=300)),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('featured', models.BooleanField(default=False, help_text='Show on the homepage featured section.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='products.category')),
                ('producer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='accounts.producerprofile')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
